version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./.devcontainer/docker/php/Dockerfile
    image: devcontainer-php:8.3-bullseye
    tty: true
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    volumes:
      - ../:/workspaces:cached
